app:added AppRouter
beastCodeDev/minzu-dem pull request #2
Opened 2024-05-25 13:02 UTC by IskenderDev

2024-05-26 06:52 UTC, beastCodeDev requested changes

2024-05-26 06:52 UTC, beastCodeDev commented on src/app/App.tsx
>        <h1 className="text-3xl font-bold underline">Hello world!</h1>
убери hello world, это было просто загрушкой

2024-05-26 06:52 UTC, beastCodeDev commented on src/app/router/config/RoouterConfig.tsx
> +enum AppRouters {
это не AppRouters, а AppRoutes

Router - это маршрутизатор, а route - это путь

в enum ты хранишь только путь, а не маршрутизатор

2024-05-26 06:52 UTC, beastCodeDev commented on src/app/router/config/RoouterConfig.tsx
> +export const Path: Record<AppRouters, string> = {
почему объект называется в большой буквы? 

не правильно сделан тип 

не правильно назван объект, не несет в себе никакого смысла, а если в нем будем много путей?

2024-05-26 06:52 UTC, beastCodeDev commented on src/app/router/ui/AppRouter.tsx
> +            {Object.values(RouterConfig).map(({element, path})=>(
у тебя space в vscode 4?

2024-05-27 05:44 UTC, beastCodeDev requested changes

2024-05-27 05:44 UTC, beastCodeDev commented on src/app/main.tsx
> +>>>>>>> 2c1514fd0ba72a96fddd368a0cc7780ba2ab0618
что это?? походу не все убрал при решении конфликтов

2024-05-27 05:44 UTC, beastCodeDev commented on src/app/router/index.ts
> +export {AppRouter}
пробелы вокруг App Router внутри фигурных скобок

2024-05-27 05:56 UTC, IskenderDev commented on src/app/router/index.ts
> +export {AppRouter}
они действтельно так важны?
И без них же код работает как надо и с ним будет работать точно также?

2024-05-27 06:02 UTC, merged