Feat/build picture card
beastCodeDev/minzu-dem pull request #5
Opened 2024-05-28 12:33 UTC by DaniyarExe

2024-05-28 13:41 UTC, asylbekovkairat requested changes

2024-05-28 13:41 UTC, asylbekovkairat commented on src/app/i18n.js
> +import Backend from 'i18next-http-backend';
после импорта нужна пустая строка

2024-05-28 13:41 UTC, asylbekovkairat commented on src/app/i18n.js
> +});
после 8 строки нужна пустая строка

2024-05-28 13:41 UTC, asylbekovkairat commented on src/entities/PaintingCard/ui/PaintingCard.tsx
сущность должна называться painting а уже в папке ui PaintingCard

2024-05-28 13:41 UTC, asylbekovkairat commented on src/entities/PaintingCard/ui/PaintingCard.tsx
> +                    <img src={ } alt="" className="rounded-md" />
пустые src

2024-05-28 13:41 UTC, asylbekovkairat commented on src/entities/PaintingCard/ui/PaintingCard.tsx
> +        <section className="flex justify-center flex-wrap gap-8 mt-14">
wrapper не должен находится в компоненте карточки, компонента карточки отвечает только за 1 карточку

2024-05-28 13:41 UTC, asylbekovkairat commented on src/entities/PaintingCard/ui/PaintingCard.tsx
> +const PaintingCard = () => {
сделать пропсы, чтобы получать данные динамически при map данных с бэкенда (бэк сделал Ильяс)

2024-05-28 13:41 UTC, asylbekovkairat commented on src/pages/home/index.ts
> +export {Home}
пустые пробелы вокруг Home внутри export

2024-05-28 13:41 UTC, asylbekovkairat commented on src/pages/home/index.ts
> +import Home from './ui/Home'
используем named export

2024-05-29 06:14 UTC, asylbekovkairat commented on src/entities/Painting/model/type.ts
> +export type TypeCard = {
неправильно назван тип, не несет в себе смысла, нужно PaintingCard

2024-05-29 10:03 UTC, beastCodeDev approved these changes

2024-05-29 12:58 UTC, closed without merging